### ISSUE TITLE
ModelServerAccess error handling created by the ModelServer

### ISSUE THREAD

**Issue by haydar-metin** [borkdominik/bigUML#65]
The errors produced in the ModelServer are not bubbled up to the GLSP-server. The `ModelServerAccess` retrieves an `OK` even if the ModelServer causes an exception. The end user / developer has therefore zero information about what happened.

Log output from ModelServer:

```
!ENTRY org.eclipse.emf.common 2 0 2022-09-28 13:16:34.133
!MESSAGE An exception was ignored during command execution
!STACK 0
org.eclipse.emf.common.util.WrappedException: An exception was ignored during command execution
	at org.eclipse.emf.common.command.BasicCommandStack.handleError(BasicCommandStack.java:281)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.handleError(AbstractTransactionalCommandStack.java:125)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:229)
	at org.eclipse.emfcloud.modelserver.emf.common.ModelServerEditingDomain.execute(ModelServerEditingDomain.java:48)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelResourceManager.executeCommand(DefaultModelResourceManager.java:508)
	at org.eclipse.emfcloud.modelserver.emf.common.RecordingModelResourceManager.executeCommand(RecordingModelResourceManager.java:55)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelResourceManager.execute(DefaultModelResourceManager.java:477)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelRepository.executeCommand(DefaultModelRepository.java:141)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.lambda$9(DefaultModelController.java:346)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:201)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.withModel(DefaultModelController.java:411)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.executeCommand(DefaultModelController.java:340)
	at org.eclipse.emfcloud.modelserver.emf.common.SingleThreadModelController.lambda$13(SingleThreadModelController.java:165)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.eclipse.emfcloud.modelserver.emf.common.SingleThreadModelController.handleAction(SingleThreadModelController.java:89)
	at org.eclipse.emfcloud.modelserver.emf.common.SingleThreadModelController.handleNextAction(SingleThreadModelController.java:83)
	at org.eclipse.emfcloud.modelserver.emf.common.SingleThreadModelController.runThread(SingleThreadModelController.java:69)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.eclipse.emf.transaction.RollbackException: Cannot cast org.eclipse.uml2.uml.internal.impl.InteractionImpl to org.eclipse.uml2.uml.Lifeline
	at org.eclipse.emf.transaction.impl.TransactionImpl.commit(TransactionImpl.java:405)
	at org.eclipse.emf.transaction.impl.TransactionalCommandStackImpl.doExecute(TransactionalCommandStackImpl.java:70)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:219)
	... 16 more
```

**Comment by haydar-metin** [comment]
modelserver has been removed from architecture
